// ============================================================
// SmartTailor AI – Demo Data & Preset Constants
// Provides realistic sample data for instant demonstration
// ============================================================

import type { Customer, FabricDetails, Order, Measurements, DressType, FabricType } from '../types';

export const DEFAULT_BODY_MEASUREMENTS: Measurements = {
  dressSize: 38,
  fullLength: 42,
  shoulderWidth: 15,
  neckWidth: 6.5,
  neckDepth: 5.5,
  armholeDepth: 8.5,
  bust: 38,
  waist: 32,
  hip: 40,
  bottomWidth: 24,
  flare: 4.5,
  ease: 1.5,
  customerName: 'Ananya Sharma',
  age: 26,
  gender: 'female',
  height: 165,
  weight: 62,
  sleeveLength: 18,
  bicepCircumference: 12,
  crossBack: 14.5,
  inseam: 29,
  outseam: 39,
  thighCircumference: 22,
};

export const FABRICS: Record<FabricType, FabricDetails> = {
  COTTON: {
    id: 'COTTON',
    name: 'Pure Cotton (Premium 60s)',
    description: 'Breathable, crisp natural cotton. Perfect for daily wear, shirts, kurtas, and frocks.',
    defaultPricePerMeter: 240,
    standardWidthInches: 44,
    drape: 'Crisp',
    breathability: 'High',
    suitableFor: ['SHIRT', 'TSHIRT', 'KURTA', 'FROCK', 'CHUDIDAR'],
    shrinkagePercent: 3,
  },
  SILK: {
    id: 'SILK',
    name: 'Raw Mulberry Silk',
    description: 'Luxurious sheen and rich texture. Ideal for saree blouses, festive kurtas, and evening gowns.',
    defaultPricePerMeter: 650,
    standardWidthInches: 44,
    drape: 'Fluid',
    breathability: 'Medium',
    suitableFor: ['BLOUSE', 'KURTA', 'FROCK', 'SKIRT'],
    shrinkagePercent: 1.5,
  },
  LINEN: {
    id: 'LINEN',
    name: 'European Organic Linen',
    description: 'Ultra-breathable with characteristic slub texture. Outstanding for bespoke shirts & trousers.',
    defaultPricePerMeter: 480,
    standardWidthInches: 58,
    drape: 'Structured',
    breathability: 'High',
    suitableFor: ['SHIRT', 'PANT', 'KURTA'],
    shrinkagePercent: 4,
  },
  DENIM: {
    id: 'DENIM',
    name: 'Selvedge Cotton Denim (12 oz)',
    description: 'Durable twill weave with structured drape. Designed for heavy-duty trousers and jackets.',
    defaultPricePerMeter: 380,
    standardWidthInches: 58,
    drape: 'Heavy',
    breathability: 'Medium',
    suitableFor: ['PANT', 'SKIRT', 'SHIRT'],
    shrinkagePercent: 2,
  },
  POLYESTER: {
    id: 'POLYESTER',
    name: 'Poly-Crepe Smooth Blend',
    description: 'Wrinkle-resistant, fast-drying, and budget-friendly with soft fall.',
    defaultPricePerMeter: 160,
    standardWidthInches: 58,
    drape: 'Fluid',
    breathability: 'Low',
    suitableFor: ['FROCK', 'BLOUSE', 'SKIRT', 'TSHIRT'],
    shrinkagePercent: 0.5,
  },
  GEORGETTE: {
    id: 'GEORGETTE',
    name: 'Viscose Georgette Chiffon',
    description: 'Lightweight, translucent crinkled crepe for graceful flow and layered ethnic wear.',
    defaultPricePerMeter: 320,
    standardWidthInches: 44,
    drape: 'Fluid',
    breathability: 'Medium',
    suitableFor: ['FROCK', 'KURTA', 'BLOUSE', 'SKIRT'],
    shrinkagePercent: 2,
  },
  VELVET: {
    id: 'VELVET',
    name: 'Plush Micro-Velvet',
    description: 'Deep pile and rich royal aesthetic. Superb for winter kurtas and designer blouses.',
    defaultPricePerMeter: 550,
    standardWidthInches: 44,
    drape: 'Heavy',
    breathability: 'Low',
    suitableFor: ['BLOUSE', 'KURTA', 'FROCK'],
    shrinkagePercent: 1,
  },
  WOOL: {
    id: 'WOOL',
    name: 'Fine Tropical Worsted Wool',
    description: 'Refined drape and thermal balance for premium formal trousers and suiting.',
    defaultPricePerMeter: 780,
    standardWidthInches: 58,
    drape: 'Structured',
    breathability: 'Medium',
    suitableFor: ['PANT', 'SKIRT'],
    shrinkagePercent: 1,
  },
};

export const DRESS_TYPE_INFO: Record<
  DressType,
  {
    label: string;
    description: string;
    icon: string;
    gender: 'Women' | 'Men' | 'Unisex' | 'All';
    baseStitchingCharge: number;
    recommendedFabric: FabricType;
    defaultLength: number;
  }
> = {
  SHIRT: {
    label: 'Formal / Casual Shirt',
    description: 'Classic button-down collar shirt with cuffed sleeves and yoke.',
    icon: '👔',
    gender: 'All',
    baseStitchingCharge: 380,
    recommendedFabric: 'COTTON',
    defaultLength: 29,
  },
  PANT: {
    label: 'Trouser / Formal Pant',
    description: 'Tailored fit trousers with waistband, side pockets, and fly zipper.',
    icon: '👖',
    gender: 'All',
    baseStitchingCharge: 450,
    recommendedFabric: 'LINEN',
    defaultLength: 40,
  },
  TSHIRT: {
    label: 'Round Neck / Polo T-Shirt',
    description: 'Comfort fit knit or woven casual tee with ribbed neckband.',
    icon: '👕',
    gender: 'All',
    baseStitchingCharge: 220,
    recommendedFabric: 'COTTON',
    defaultLength: 27,
  },
  KURTA: {
    label: 'Traditional Kurta / Kurti',
    description: 'Straight or A-line silhouette with side slits and mandarin collar.',
    icon: '🥻',
    gender: 'All',
    baseStitchingCharge: 420,
    recommendedFabric: 'COTTON',
    defaultLength: 44,
  },
  BLOUSE: {
    label: 'Fitted Saree Blouse',
    description: 'Close-fitting bodice with front/back darts, hook closure, and lining.',
    icon: '👚',
    gender: 'Women',
    baseStitchingCharge: 480,
    recommendedFabric: 'SILK',
    defaultLength: 15,
  },
  CHUDIDAR: {
    label: 'Chudidar / Salwar Bottom',
    description: 'Gathered ankle gathers or pleated salwar with drawstring waistband.',
    icon: '🩳',
    gender: 'Women',
    baseStitchingCharge: 300,
    recommendedFabric: 'COTTON',
    defaultLength: 42,
  },
  FROCK: {
    label: 'One-Piece Dress / Frock',
    description: 'Fitted bodice transitioning into a flared skirt hem with darts.',
    icon: '👗',
    gender: 'Women',
    baseStitchingCharge: 550,
    recommendedFabric: 'SILK',
    defaultLength: 48,
  },
  SKIRT: {
    label: 'A-Line / Flared Skirt',
    description: 'High-waisted flowing skirt with waistband and concealed zip.',
    icon: '💃',
    gender: 'Women',
    baseStitchingCharge: 320,
    recommendedFabric: 'LINEN',
    defaultLength: 36,
  },
};

export const COLOR_PALETTE = [
  { name: 'Royal Navy', hex: '#1E3A8A', dark: true },
  { name: 'Emerald Green', hex: '#065F46', dark: true },
  { name: 'Burgundy Wine', hex: '#881337', dark: true },
  { name: 'Champagne Gold', hex: '#D97706', dark: false },
  { name: 'Charcoal Black', hex: '#18181B', dark: true },
  { name: 'Blush Rose', hex: '#BE185D', dark: false },
  { name: 'Sage Olive', hex: '#4D7C0F', dark: false },
  { name: 'Terracotta', hex: '#C2410C', dark: false },
  { name: 'Ivory White', hex: '#F8FAFC', dark: false },
  { name: 'Imperial Purple', hex: '#6D28D9', dark: true },
  { name: 'Sky Blue', hex: '#0284C7', dark: false },
  { name: 'Mocha Brown', hex: '#78350F', dark: true },
];

export const DEMO_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Priya Sundaram',
    phone: '+91 98401 23456',
    email: 'priya.s@example.com',
    age: 28,
    gender: 'female',
    height: 163,
    weight: 58,
    createdAt: '2026-08-15',
    totalOrdersCount: 3,
    notes: 'Prefers 1.5" ease on bust. Likes soft lining in silk blouses.',
    measurements: {
      dressSize: 36,
      fullLength: 46,
      shoulderWidth: 14.5,
      neckWidth: 6,
      neckDepth: 6,
      armholeDepth: 8,
      bust: 36,
      waist: 29,
      hip: 38,
      bottomWidth: 26,
      flare: 5,
      ease: 1.5,
      customerName: 'Priya Sundaram',
      age: 28,
      gender: 'female',
      height: 163,
      weight: 58,
      sleeveLength: 17,
      bicepCircumference: 11.5,
    },
  },
  {
    id: 'cust-2',
    name: 'Rahul Varma',
    phone: '+91 97112 88990',
    email: 'rahul.v@example.com',
    age: 32,
    gender: 'male',
    height: 178,
    weight: 76,
    createdAt: '2026-08-18',
    totalOrdersCount: 2,
    notes: 'Slim fit shirts. 0.5" extra length on sleeves.',
    measurements: {
      dressSize: 40,
      fullLength: 30,
      shoulderWidth: 18,
      neckWidth: 16,
      neckDepth: 2,
      armholeDepth: 9.5,
      bust: 40,
      waist: 34,
      hip: 41,
      bottomWidth: 22,
      flare: 0,
      ease: 2,
      customerName: 'Rahul Varma',
      age: 32,
      gender: 'male',
      height: 178,
      weight: 76,
      sleeveLength: 25,
      crossBack: 17.5,
      inseam: 32,
      outseam: 41,
    },
  },
  {
    id: 'cust-3',
    name: 'Meera Nambiar',
    phone: '+91 94470 54321',
    email: 'meera.n@example.com',
    age: 24,
    gender: 'female',
    height: 158,
    weight: 52,
    createdAt: '2026-08-22',
    totalOrdersCount: 1,
    notes: 'Anarkali flared frocks and Saree blouse specialist measurements.',
    measurements: {
      dressSize: 34,
      fullLength: 50,
      shoulderWidth: 14,
      neckWidth: 5.5,
      neckDepth: 6.5,
      armholeDepth: 7.5,
      bust: 34,
      waist: 27,
      hip: 36,
      bottomWidth: 32,
      flare: 7,
      ease: 1.5,
      customerName: 'Meera Nambiar',
      age: 24,
      gender: 'female',
      height: 158,
      weight: 52,
      sleeveLength: 15,
    },
  },
  {
    id: 'cust-4',
    name: 'Vikramaditya Roy',
    phone: '+91 98300 11223',
    email: 'vikram.roy@example.com',
    age: 45,
    gender: 'male',
    height: 172,
    weight: 82,
    createdAt: '2026-08-25',
    totalOrdersCount: 4,
    notes: 'Tailored trousers in wool and linen. Prefers regular comfort rise.',
    measurements: {
      dressSize: 42,
      fullLength: 41,
      shoulderWidth: 18.5,
      neckWidth: 16.5,
      neckDepth: 2,
      armholeDepth: 10,
      bust: 42,
      waist: 38,
      hip: 44,
      bottomWidth: 19,
      flare: 0,
      ease: 2,
      customerName: 'Vikramaditya Roy',
      age: 45,
      gender: 'male',
      height: 172,
      weight: 82,
      inseam: 30,
      outseam: 41,
    },
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'ST-2026-001',
    customerId: 'cust-1',
    customerName: 'Priya Sundaram',
    customerPhone: '+91 98401 23456',
    customerEmail: 'priya.s@example.com',
    dressType: 'FROCK',
    fabricType: 'SILK',
    fabricColor: '#881337',
    fabricLengthMeters: 3.2,
    measurements: DEMO_CUSTOMERS[0].measurements,
    totalCost: 3120,
    currency: 'INR',
    status: 'delivered',
    paymentStatus: 'fully_paid',
    orderDate: '2026-08-16',
    deliveryDueDate: '2026-08-23',
    notes: 'Burgundy wine silk party frock with golden border lining.',
    costBreakdown: {
      garmentType: 'FROCK',
      fabricType: 'SILK',
      requiredLengthMeters: 3.2,
      requiredLengthYards: 3.5,
      usableFabricMeters: 2.94,
      estimatedWasteMeters: 0.26,
      fabricWidthInches: 44,
      pricePerMeter: 650,
      fabricCost: 2080,
      baseStitchingCharge: 550,
      addOnCharges: {
        lining: 250,
        embroidery: 200,
        buttons: 40,
        express: 0,
        customization: 0,
      },
      totalAddOns: 490,
      subtotal: 3120,
      taxPercent: 0,
      taxAmount: 0,
      discountAmount: 0,
      totalCost: 3120,
      cuttingWasteEstimatePercent: 8,
      fabricLayoutSuggestion: 'Bias cut for flare panel with 2-panel bodice layout',
    },
  },
  {
    id: 'ord-102',
    orderNumber: 'ST-2026-002',
    customerId: 'cust-2',
    customerName: 'Rahul Varma',
    customerPhone: '+91 97112 88990',
    customerEmail: 'rahul.v@example.com',
    dressType: 'SHIRT',
    fabricType: 'LINEN',
    fabricColor: '#1E3A8A',
    fabricLengthMeters: 1.8,
    measurements: DEMO_CUSTOMERS[1].measurements,
    totalCost: 1424,
    currency: 'INR',
    status: 'ready',
    paymentStatus: 'deposit_paid',
    orderDate: '2026-08-22',
    deliveryDueDate: '2026-08-29',
    notes: 'Spread collar with mother of pearl buttons.',
    costBreakdown: {
      garmentType: 'SHIRT',
      fabricType: 'LINEN',
      requiredLengthMeters: 1.8,
      requiredLengthYards: 1.97,
      usableFabricMeters: 1.69,
      estimatedWasteMeters: 0.11,
      fabricWidthInches: 58,
      pricePerMeter: 480,
      fabricCost: 864,
      baseStitchingCharge: 380,
      addOnCharges: {
        lining: 0,
        embroidery: 0,
        buttons: 100,
        express: 0,
        customization: 80,
      },
      totalAddOns: 180,
      subtotal: 1424,
      taxPercent: 0,
      taxAmount: 0,
      discountAmount: 0,
      totalCost: 1424,
      cuttingWasteEstimatePercent: 6,
      fabricLayoutSuggestion: 'Lengthwise grain with split back yoke',
    },
  },
  {
    id: 'ord-103',
    orderNumber: 'ST-2026-003',
    customerId: 'cust-3',
    customerName: 'Meera Nambiar',
    customerPhone: '+91 94470 54321',
    customerEmail: 'meera.n@example.com',
    dressType: 'BLOUSE',
    fabricType: 'SILK',
    fabricColor: '#D97706',
    fabricLengthMeters: 1.0,
    measurements: DEMO_CUSTOMERS[2].measurements,
    totalCost: 1530,
    currency: 'INR',
    status: 'stitching',
    paymentStatus: 'deposit_paid',
    orderDate: '2026-08-26',
    deliveryDueDate: '2026-09-03',
    specialInstructions: 'Sweetheart neck with deep back and zari lace work.',
    notes: 'Sweetheart neck with deep back and zari lace work.',
    costBreakdown: {
      garmentType: 'BLOUSE',
      fabricType: 'SILK',
      requiredLengthMeters: 1.0,
      requiredLengthYards: 1.09,
      usableFabricMeters: 0.95,
      estimatedWasteMeters: 0.05,
      fabricWidthInches: 44,
      pricePerMeter: 650,
      fabricCost: 650,
      baseStitchingCharge: 480,
      addOnCharges: {
        lining: 150,
        embroidery: 250,
        buttons: 0,
        express: 0,
        customization: 0,
      },
      totalAddOns: 400,
      subtotal: 1530,
      taxPercent: 0,
      taxAmount: 0,
      discountAmount: 0,
      totalCost: 1530,
      cuttingWasteEstimatePercent: 5,
      fabricLayoutSuggestion: 'Cross grain sleeves with padded bust cup lining',
    },
  },
  {
    id: 'ord-104',
    orderNumber: 'ST-2026-004',
    customerId: 'cust-4',
    customerName: 'Vikramaditya Roy',
    customerPhone: '+91 98300 11223',
    customerEmail: 'vikram.roy@example.com',
    dressType: 'PANT',
    fabricType: 'WOOL',
    fabricColor: '#18181B',
    fabricLengthMeters: 1.4,
    measurements: DEMO_CUSTOMERS[3].measurements,
    totalCost: 1842,
    currency: 'INR',
    status: 'cutting',
    paymentStatus: 'unpaid',
    orderDate: '2026-08-30',
    deliveryDueDate: '2026-09-06',
    specialInstructions: 'Charcoal formal trousers, double pleats with watch pocket.',
    notes: 'Charcoal formal trousers, double pleats with watch pocket.',
    costBreakdown: {
      garmentType: 'PANT',
      fabricType: 'WOOL',
      requiredLengthMeters: 1.4,
      requiredLengthYards: 1.53,
      usableFabricMeters: 1.3,
      estimatedWasteMeters: 0.1,
      fabricWidthInches: 58,
      pricePerMeter: 780,
      fabricCost: 1092,
      baseStitchingCharge: 450,
      addOnCharges: {
        lining: 120,
        embroidery: 0,
        buttons: 60,
        express: 120,
        customization: 0,
      },
      totalAddOns: 300,
      subtotal: 1842,
      taxPercent: 0,
      taxAmount: 0,
      discountAmount: 0,
      totalCost: 1842,
      cuttingWasteEstimatePercent: 7,
      fabricLayoutSuggestion: 'Two-way lengthwise lay with pocket facing',
    },
  },
];
